### ISSUE TITLE
Program.cs in the 'csharp-program-flow' of the 'module-05-bonus

### ISSUE THREAD

**Issue by MaddHatterHX** [alex-wolf-ps/csharp-program-flow#1]
I haven't  checked to confirm this is the case with the other versions also, but when attempting to quit the console app the user is then prompted to specify the quarter of data instead of immediately quitting.  

Even though this is merely a teaching example Would it not be better to wrap the switch statement in an if-then selector to immediately quit the app if the user types in 'quit' instead of including it within the switch block of the 'selectedReport' variable?

https://github.com/alex-wolf-ps/csharp-program-flow/blob/87b0fd8dce9a821d27e5ff9bde45c038f5a326f9/WiredBrainCoffeeSurveys.Reports/Program.cs#L22

class Program
    {
        static void Main(string[] args)
        {
            bool quitApp = false;
            do
            {
                Console.WriteLine("Please specify a report to run (rewards, comments, tasks, quit):");
                var selectedReport = Console.ReadLine();

                if (selectedReport == "quit")
                {
                    quitApp = true;
                }
                else { 
                Console.WriteLine("Please specify which quarter of data: (q1, q2)");
                var selectedData = Console.ReadLine();

                var surveyResults = SurveyDataService.GetSurveyDataByFileName(selectedData);

                    switch (selectedReport)
                    {
                        case "rewards":
                            RewardsReportService.GenerateWinnerEmails(surveyResults);
                            break;
                        case "comments":
                            CommentsReportService.GenerateCommentsReport(surveyResults);
                            break;
                        case "tasks":
                            TasksReportService.GenerateTasksReport(surveyResults);
                            break;
                        default:
                            Console.WriteLine("Sorry, that's not a valid option.");
                            break;
                    }
                    Console.WriteLine();
                }
            }
            while (!quitApp);
        }
    }

Sorry, I couldn't get the file to upload so I included my example in-line.  

Thank you for the class, it has been very informative!

**Comment by alex-wolf-ps** [comment]
Hey, thank you for pointing this out.  After looking this over again I"m realizing the "quit" functionality makes sense when I initially implement it, but when I enhance the app with additional features in later videos, I didn't fix the "quit" and move it earlier in the process (like you did here). The final state of the app has been updated to match what you have here.

**Comment by MaddHatterHX** [comment]
Excellent!  I'm pleased my contribution helped!  Thank you again for your training videos!  Clearly they've helped :)
